"""
Synthetic security-log generator with ground-truth PII/PHI annotations.

Produces a JSONL file where each line is:
  {"log": "<raw log text>", "log_type": "windows_event|syslog|cloudtrail",
   "pii": [{"start": int, "end": int, "type": "EMAIL|SSN|CREDIT_CARD|PERSON|IP|MRN"}]}

No real data. All identifiers are generated by Faker with a fixed seed for
reproducibility. Ground-truth offsets are located by substring search against
the generated values themselves (each value is unique per entry given the
random seed), which sidesteps template-parsing edge cases entirely.
"""
import json
import random
import argparse
from faker import Faker

fake = Faker()
Faker.seed(42)
random.seed(42)


def make_slots() -> dict:
    return {
        "PERSON_name": fake.name(),
        "PERSON_name_flat": fake.user_name(),
        "IP_addr": fake.ipv4_public(),
        "EMAIL_addr": fake.email(),
        "SSN_num": fake.ssn(),
        "MRN_id": f"MRN-{fake.random_number(digits=7, fix_len=True)}",
        "CREDIT_CARD_num": fake.credit_card_number(),
        "num": random.randint(1, 9999),
        "pid": random.randint(1000, 9999),
        "port": random.randint(1024, 65535),
        "ts": fake.iso8601(),
    }


def slot_pii_type(key: str) -> str | None:
    prefix = key.split("_")[0].upper()
    return prefix if prefix in {"EMAIL", "SSN", "CREDIT", "PERSON", "IP", "MRN"} else None


PII_TYPE_MAP = {"CREDIT": "CREDIT_CARD"}


def render(template: str, slots: dict, used_keys: list[str]) -> tuple[str, list[dict]]:
    text = template.format(**slots)
    spans = []
    for key in used_keys:
        pii_type = slot_pii_type(key)
        if pii_type is None:
            continue
        pii_type = PII_TYPE_MAP.get(pii_type, pii_type)
        value = str(slots[key])
        start = text.find(value)
        if start == -1:
            continue
        spans.append({"start": start, "end": start + len(value), "type": pii_type})
    spans.sort(key=lambda s: s["start"])
    return text, spans


WINDOWS_TEMPLATES = [
    ("EventID=4624 LogonType=3 TargetUserName={PERSON_name} TargetDomainName=CORP "
     "IpAddress={IP_addr} WorkstationName=WS-{num:04d} LogonProcessName=NtLmSsp",
     ["PERSON_name", "IP_addr"]),
    ("EventID=4688 NewProcessName=C:\\Windows\\System32\\cmd.exe SubjectUserName={PERSON_name} "
     "SubjectDomainName=CORP CommandLine=whoami",
     ["PERSON_name"]),
    ("EventID=4625 LogonType=3 TargetUserName={PERSON_name} FailureReason=%%2313 "
     "IpAddress={IP_addr} Status=0xC000006D",
     ["PERSON_name", "IP_addr"]),
]

SYSLOG_TEMPLATES = [
    ("sshd[{pid}]: Failed password for {PERSON_name_flat} from {IP_addr} port {port} ssh2",
     ["PERSON_name_flat", "IP_addr"]),
    ("sudo[{pid}]: {PERSON_name_flat} : TTY=pts/0 ; PWD=/home/{PERSON_name_flat} ; "
     "USER=root ; COMMAND=/usr/bin/systemctl restart nginx",
     ["PERSON_name_flat"]),
    ("kernel: [{ts}] iptables: DROP IN=eth0 SRC={IP_addr} DST=10.0.0.1 PROTO=TCP",
     ["IP_addr"]),
]

CLOUDTRAIL_TEMPLATES = [
    ('{{"eventName": "PutObject", "sourceIPAddress": "{IP_addr}", '
     '"userIdentity": {{"userName": "{PERSON_name_flat}", "email": "{EMAIL_addr}"}}, '
     '"requestParameters": {{"bucketName": "app-data", "key": "uploads/{num}.csv"}}}}',
     ["IP_addr", "PERSON_name_flat", "EMAIL_addr"]),
    ('{{"eventName": "UpdateUser", "sourceIPAddress": "{IP_addr}", '
     '"userIdentity": {{"userName": "svc-deploy"}}, '
     '"requestParameters": {{"targetUser": "{PERSON_name_flat}", "notes": "SSN on file: {SSN_num}"}}}}',
     ["IP_addr", "PERSON_name_flat", "SSN_num"]),
    ('{{"eventName": "GetPatientRecord", "sourceIPAddress": "{IP_addr}", '
     '"userIdentity": {{"userName": "{PERSON_name_flat}"}}, '
     '"requestParameters": {{"mrn": "{MRN_id}", "reason": "billing reconciliation"}}}}',
     ["IP_addr", "PERSON_name_flat", "MRN_id"]),
    ('{{"eventName": "UpdatePaymentMethod", "sourceIPAddress": "{IP_addr}", '
     '"userIdentity": {{"userName": "{PERSON_name_flat}"}}, '
     '"requestParameters": {{"cardNumber": "{CREDIT_CARD_num}", "billingEmail": "{EMAIL_addr}"}}}}',
     ["IP_addr", "PERSON_name_flat", "CREDIT_CARD_num", "EMAIL_addr"]),
]

CLEAN_TEMPLATES = {
    "windows_event": [
        "EventID=4634 LogonType=3 TargetUserName=SYSTEM TargetDomainName=NT_AUTHORITY",
        "EventID=4672 SubjectUserName=SYSTEM PrivilegeList=SeDebugPrivilege",
    ],
    "syslog": [
        "systemd[1]: Started Session {num} of user root.",
        "kernel: [{ts}] CPU0: Package temperature above threshold, cpu clock throttled",
    ],
    "cloudtrail": [
        '{{"eventName": "DescribeInstances", "sourceIPAddress": "10.0.0.5", '
        '"userIdentity": {{"userName": "svc-monitor"}}, "requestParameters": {{}}}}',
    ],
}


def build_entry(log_type: str, dirty: bool) -> dict:
    slots = make_slots()
    if not dirty:
        template = random.choice(CLEAN_TEMPLATES[log_type])
        text = template.format(**slots)
        return {"log": text, "log_type": log_type, "pii": []}

    if log_type == "windows_event":
        template, used_keys = random.choice(WINDOWS_TEMPLATES)
    elif log_type == "syslog":
        template, used_keys = random.choice(SYSLOG_TEMPLATES)
    else:
        template, used_keys = random.choice(CLOUDTRAIL_TEMPLATES)

    text, spans = render(template, slots, used_keys)
    return {"log": text, "log_type": log_type, "pii": spans}


def main(n: int, out_path: str, dirty_ratio: float = 0.3):
    log_types = ["windows_event", "syslog", "cloudtrail"]
    with open(out_path, "w") as f:
        for _ in range(n):
            log_type = random.choice(log_types)
            dirty = random.random() < dirty_ratio
            entry = build_entry(log_type, dirty)
            f.write(json.dumps(entry) + "\n")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--n", type=int, default=5000)
    parser.add_argument("--out", type=str, default="data/synthetic_logs.jsonl")
    parser.add_argument("--dirty-ratio", type=float, default=0.3)
    args = parser.parse_args()
    main(args.n, args.out, args.dirty_ratio)
    print(f"Wrote {args.n} entries to {args.out}")
